PrivateKey = {Path = "/pk/test-member.keystore", Password = "password"} # CHANGE THIS (the password): according to the private key file password
FireblocksFeatureEnabled = true

[L1]
WsURL = "wss://eth-sepolia.g.alchemy.com/v2/cU_hSlUcnHTsHQqz48Z6fuzbfM0qc2bq"     # CHANGE THIS: use the URL of your L1 node
RpcURL = "https://eth-sepolia.g.alchemy.com/v2/cU_hSlUcnHTsHQqz48Z6fuzbfM0qc2bq"  # CHANGE THIS: use the URL of your L1 node
PolygonValidiumAddress = "0x72B2d2CE98A759b57B2db8e2A34997B710F07Bd6"       # CHANGE THIS: Address of the Validium smart contract
DataCommitteeAddress = "0x01C0942b66c08a5B7919e496cB7B1631921CBa17"     # CHANGE THIS: Address of the data availability committee smart contract
Timeout = "3m"
RetryPeriod = "5s"
BlockBatchSize = 32

[Log]
Environment = "development" # "production" or "development"
Level = "debug"
Outputs = ["stderr"]

[DB]
User = "committee_user"             # CHANGE THIS: according to the POSTGRES_USER in docker-compose.yml
Password = "committee_password"     # CHANGE THIS: according to the POSTGRES_PASSWORD in docker-compose.yml
Name = "committee_db"
Host = "cdk-data-availability-db"
Port = "5432"
EnableLog = false
MaxConns = 200

[RPC]
Host = "0.0.0.0"
Port = 8444
ReadTimeout = "60s"
WriteTimeout = "60s"
MaxRequestsPerIPAndSecond = 500
