PrivateKey = {Path = "/pk/test-member.keystore", Password = "password"} # CHANGE THIS (the password): according to the private key file password
FireblocksFeatureEnabled = true

[L1]
WsURL = "wss://eth-sepolia.g.alchemy.com/v2/cU_hSlUcnHTsHQqz48Z6fuzbfM0qc2bq"     # CHANGE THIS: use the URL of your L1 node
RpcURL = "https://eth-sepolia.g.alchemy.com/v2/cU_hSlUcnHTsHQqz48Z6fuzbfM0qc2bq"  # CHANGE THIS: use the URL of your L1 node
PolygonValidiumAddress = "0xae119dA2C2341A1afF2449A8e85267412908eF04"       # CHANGE THIS: Address of the Validium smart contract
DataCommitteeAddress = "0x2e1688C6FEb6B83810647b5A3C18360dA4815c23"     # CHANGE THIS: Address of the data availability committee smart contract
Timeout = "3m"
RetryPeriod = "5s"
BlockBatchSize = 32

[Log]
Environment = "development" # "production" or "development"
Level = "debug"
Outputs = ["stderr"]

[DB]
User = "committee_user"             # CHANGE THIS: according to the POSTGRES_USER in docker-compose.yml
Password = "committee_password"     # CHANGE THIS: according to the POSTGRES_PASSWORD in docker-compose.yml
Name = "committee_db"
Host = "cdk-data-availability-db"
Port = "5432"
EnableLog = false
MaxConns = 200

[RPC]
Host = "0.0.0.0"
Port = 8444
ReadTimeout = "60s"
WriteTimeout = "60s"
MaxRequestsPerIPAndSecond = 500
