PrivateKey = {Path = "/pk/test-member.keystore", Password = "password"} # CHANGE THIS (the password): according to the private key file password
DACAddress="0x3338E5e5CA534c6b9b224Fa9a8621274b4719641"
[L1]
WsURL = "wss://eth-sepolia.g.alchemy.com/v2/cU_hSlUcnHTsHQqz48Z6fuzbfM0qc2bq"     # CHANGE THIS: use the URL of your L1 node
RpcURL = "https://eth-sepolia.g.alchemy.com/v2/cU_hSlUcnHTsHQqz48Z6fuzbfM0qc2bq"  # CHANGE THIS: use the URL of your L1 node
PolygonValidiumAddress = "0x3f0228584745dbcEb03AA8af73A079cd4a070D21"       # CHANGE THIS: Address of the Validium smart contract
DataCommitteeAddress = "0x033aA5eA457Fc80921e67cB2Ee1e1f888f03851A"     # CHANGE THIS: Address of the data availability committee smart contract
Timeout = "3m"
RetryPeriod = "5s"
BlockBatchSize = 32

[Log]
Environment = "development" # "production" or "development"
Level = "debug"
Outputs = ["stderr"]

[DB]
User = "committee_user"             # CHANGE THIS: according to the POSTGRES_USER in docker-compose.yml
Password = "committee_password"     # CHANGE THIS: according to the POSTGRES_PASSWORD in docker-compose.yml
Name = "committee_db"
Host = "cdk-data-availability-db"
Port = "5432"
EnableLog = false
MaxConns = 200

[RPC]
Host = "0.0.0.0"
Port = 8444
ReadTimeout = "60s"
WriteTimeout = "60s"
MaxRequestsPerIPAndSecond = 500
